export const professions = [
    { label: 'Administrador(a)', value: 'Administrador(a)' },
    { label: 'Advogado(a)', value: 'Advogado(a)' },
    { label: 'Agricultor(a)', value: 'Agricultor(a)' },
    { label: 'Analista de Sistemas', value: 'Analista de Sistemas' },
    { label: 'Aposentado(a)', value: 'Aposentado(a)' },
    { label: 'Arquiteto(a)', value: 'Arquiteto(a)' },
    { label: 'Artesão(ã)', value: 'Artesão(ã)' },
    { label: 'Assistente Administrativo', value: 'Assistente Administrativo' },
    { label: 'Assistente Social', value: 'Assistente Social' },
    { label: 'Atendente', value: 'Atendente' },
    { label: 'Autônomo(a)', value: 'Autônomo(a)' },
    { label: 'Auxiliar de Cozinha', value: 'Auxiliar de Cozinha' },
    { label: 'Auxiliar de Limpeza', value: 'Auxiliar de Limpeza' },
    { label: 'Auxiliar Geral', value: 'Auxiliar Geral' },
    { label: 'Bancário(a)', value: 'Bancário(a)' },
    { label: 'Biólogo(a)', value: 'Biólogo(a)' },
    { label: 'Bombeiro(a)', value: 'Bombeiro(a)' },
    { label: 'Cabeleireiro(a)', value: 'Cabeleireiro(a)' },
    { label: 'Caixa', value: 'Caixa' },
    { label: 'Caminhoneiro(a)', value: 'Caminhoneiro(a)' },
    { label: 'Carpinteiro(a)', value: 'Carpinteiro(a)' },
    { label: 'Chef de Cozinha', value: 'Chef de Cozinha' },
    { label: 'Cientista', value: 'Cientista' },
    { label: 'Comerciante', value: 'Comerciante' },
    { label: 'Consultor(a)', value: 'Consultor(a)' },
    { label: 'Contador(a)', value: 'Contador(a)' },
    { label: 'Corretor(a) de Imóveis', value: 'Corretor(a) de Imóveis' },
    { label: 'Corretor(a) de Seguros', value: 'Corretor(a) de Seguros' },
    { label: 'Cozinheiro(a)', value: 'Cozinheiro(a)' },
    { label: 'Dentista', value: 'Dentista' },
    { label: 'Designer Gráfico', value: 'Designer Gráfico' },
    { label: 'Digitador(a)', value: 'Digitador(a)' },
    { label: 'Diretor(a)', value: 'Diretor(a)' },
    { label: 'Dona de Casa', value: 'Dona de Casa' },
    { label: 'Economista', value: 'Economista' },
    { label: 'Educador(a) Físico', value: 'Educador(a) Físico' },
    { label: 'Eletricista', value: 'Eletricista' },
    { label: 'Empreendedor(a)', value: 'Empreendedor(a)' },
    { label: 'Enfermeiro(a)', value: 'Enfermeiro(a)' },
    { label: 'Engenheiro(a) Civil', value: 'Engenheiro(a) Civil' },
    { label: 'Engenheiro(a) Eletricista', value: 'Engenheiro(a) Eletricista' },
    { label: 'Engenheiro(a) Mecânico', value: 'Engenheiro(a) Mecânico' },
    { label: 'Escritor(a)', value: 'Escritor(a)' },
    { label: 'Estagiário(a)', value: 'Estagiário(a)' },
    { label: 'Esteticista', value: 'Esteticista' },
    { label: 'Estudante', value: 'Estudante' },
    { label: 'Farmacêutico(a)', value: 'Farmacêutico(a)' },
    { label: 'Faxineiro(a)', value: 'Faxineiro(a)' },
    { label: 'Fiscal', value: 'Fiscal' },
    { label: 'Fisioterapeuta', value: 'Fisioterapeuta' },
    { label: 'Fotógrafo(a)', value: 'Fotógrafo(a)' },
    { label: 'Funcionário(a) Público', value: 'Funcionário(a) Público' },
    { label: 'Garçom/Garçonete', value: 'Garçom/Garçonete' },
    { label: 'Gerente', value: 'Gerente' },
    { label: 'Guia de Turismo', value: 'Guia de Turismo' },
    { label: 'Instalador(a)', value: 'Instalador(a)' },
    { label: 'Jornalista', value: 'Jornalista' },
    { label: 'Juiz(a)', value: 'Juiz(a)' },
    { label: 'Manicure/Pedicure', value: 'Manicure/Pedicure' },
    { label: 'Maquiador(a)', value: 'Maquiador(a)' },
    { label: 'Marceneiro(a)', value: 'Marceneiro(a)' },
    { label: 'Mecânico(a)', value: 'Mecânico(a)' },
    { label: 'Médico(a)', value: 'Médico(a)' },
    { label: 'Militar', value: 'Militar' },
    { label: 'Motorista de Aplicativo', value: 'Motorista de Aplicativo' },
    { label: 'Motorista Particular', value: 'Motorista Particular' },
    { label: 'Músico(a)', value: 'Músico(a)' },
    { label: 'Nutricionista', value: 'Nutricionista' },
    { label: 'Odontologista', value: 'Odontologista' },
    { label: 'Operador(a) de Telemarketing', value: 'Operador(a) de Telemarketing' },
    { label: 'Operário(a)', value: 'Operário(a)' },
    { label: 'Padeiro(a)', value: 'Padeiro(a)' },
    { label: 'Pedreiro(a)', value: 'Pedreiro(a)' },
    { label: 'Piloto(a)', value: 'Piloto(a)' },
    { label: 'Pintor(a)', value: 'Pintor(a)' },
    { label: 'Policial', value: 'Policial' },
    { label: 'Porteiro(a)', value: 'Porteiro(a)' },
    { label: 'Professor(a)', value: 'Professor(a)' },
    { label: 'Programador(a)', value: 'Programador(a)' },
    { label: 'Psicólogo(a)', value: 'Psicólogo(a)' },
    { label: 'Publicitário(a)', value: 'Publicitário(a)' },
    { label: 'Recepcionista', value: 'Recepcionista' },
    { label: 'Representante Comercial', value: 'Representante Comercial' },
    { label: 'Secretário(a)', value: 'Secretário(a)' },
    { label: 'Segurança', value: 'Segurança' },
    { label: 'Servidor(a) Público', value: 'Servidor(a) Público' },
    { label: 'Soldador(a)', value: 'Soldador(a)' },
    { label: 'Técnico(a) em Edificações', value: 'Técnico(a) em Edificações' },
    { label: 'Técnico(a) em Enfermagem', value: 'Técnico(a) em Enfermagem' },
    { label: 'Técnico(a) em Informática', value: 'Técnico(a) em Informática' },
    { label: 'Terapeuta Ocupacional', value: 'Terapeuta Ocupacional' },
    { label: 'Vendedor(a)', value: 'Vendedor(a)' },
    { label: 'Veterinário(a)', value: 'Veterinário(a)' },
    { label: 'Vigilante', value: 'Vigilante' },
    { label: 'Web Designer', value: 'Web Designer' },
    { label: 'Zelador(a)', value: 'Zelador(a)' }
].sort((a, b) => a.label.localeCompare(b.label));
